### ISSUE TITLE
AddCommand effects isnot work in iOS

### ISSUE THREAD

**Issue by mrxten** [muak/AiForms.Effects#12]
I tried use EffectColor for BoxView and Grid and isnt work. How to solve problem?
And yes, I called Init method in AppDelegate.

**Comment by muak** [comment]
@mrxten 
Thank you for trying it.
I will investigate about the issue.
Please wait for a while.

**Comment by mrxten** [comment]
I meant effect color does not work for ios, if there not command. Can you change it? :)

**Comment by muak** [comment]
@mrxten 
Sorry, color not changing  when there is not command  is normal behavior.
How about use void command ?
```cs
public Command VoidCommand{get;set;}

public ViewModel(){
    VoidCommand = new Command( _ => {});
}
```
```xml
<Label ef:AddCommand.Command="{Binding VoidCommand}" ... />
```

**Comment by mrxten** [comment]
@muak, but in Android works without command. You will not change it?

**Comment by muak** [comment]
@mrxten 
Certainly. 
But I would rather fix not to change color when command is null on Android than iOS change.

**Comment by mrxten** [comment]
But if I want change effect color by tap without command?
This would be good.
Anyway thanks for your library :)
