### ISSUE TITLE
カスタムレンダラーを使いAndroidでのImageViewにもToFlatButtonを適用することはできますか？

### ISSUE THREAD

**Issue by yuki2006** [muak/AiForms.Effects#20]
こんにちは。こちらのライブラリを有りがたく使わせていただいております。
（英語が苦手なので日本語で失礼します）

Xamarin.Formsの標準の使い方ではないのですが、
ButtonにImageを入れたかったのでカスタムレンダラーでAppCompatImageButtonを使うようにしており、その上でこちらのライブラリの恩恵も受けたいと思っていたのですがAppCompatButtonでしか適用されないようで（さらにOnDettach時に落ちる）、
もしよろしければAppCompatImageButtonでも枠線や背景などを変更できるようにご検討できないでしょうか？

AndroidではImageButtonとButtonは継承関係になっていないのがネックかと思われ、
実現できるかどうかもわかりませんが、ご検討いただければ幸いです。

**Comment by muak** [comment]
@yuki2006 
ご利用ありがとうございます！

ButtonとImageButtonは別物のようなのでToFlatButtonのEffectで処理するのは修正で対応するのは難しいですね。
カスタムレンダラーを作っているようであればそのレンダラーに枠線や背景の処理を実装した方が良いと思います。基本的にEffectでもCustomRendererでも同じような方法で対応できるのでEffectのソースをコピペして適宜修正するというもので対応できそうな気がします。
あるいは画像をタップに対応させるだけでよければImageにCommandEffect（TapGestureRecognizer）を付けたものにBorderEffectを組み合わせても近いものが実現できるかもしれません。
