### ISSUE TITLE
Android 5.0 (API-21) ToFlatButton crash

### ISSUE THREAD

**Issue by alexpetin** [muak/AiForms.Effects#21]
XF app with button.ToFlatButton.On=True work great on API > 21, but crashes on API-21.
There are a LOT of output in log related to this crash, but I think it's the reason:

09-27 19:31:50.481 3953-3953/com.liwm.android A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: can't call void android.view.View.setTranslationZ(float) on null object
09-27 19:31:50.481 3953-3953/com.liwm.android A/art: art/runtime/check_jni.cc:65]     in call to CallVoidMethodV
09-27 19:31:50.481 3953-3953/com.liwm.android A/art: art/runtime/check_jni.cc:65]     from void android.animation.PropertyValuesHolder.nCallFloatMethod(java.lang.Object, long, float)
09-27 19:31:50.481 3953-3953/com.liwm.android A/art: art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable

**Comment by muak** [comment]
@alexpetin 
I'm sorry that I have made a mistake of Readme.md.
Correct minimum is Android 5.1.1 (API22).

If possible, could you please use Api22?

I will fix Readme.md later.

**Comment by alexpetin** [comment]
Thank you for response.
No way to support API-21?

**Comment by muak** [comment]
@alexpetin 
I'm afraid not.
I think that how to customize Api21 is different from  Api22 or later.
