### ISSUE TITLE
Add feedback options (EffectColor, EnableRipple, EnableSound, SyncCanExecute) to AddDatePicker and AddTimePicker

### ISSUE THREAD

**Issue by alexpetin** [muak/AiForms.Effects#24]
It would be great to have tap feedback options in AddTimePicker & AddDatePicker like the ones at AddCommand.

**Comment by muak** [comment]
@alexpetin 
Noted with thanks.
I think  I will add these options at next version(1.1.0) or later😇
Please wait for some while.

**Comment by alexpetin** [comment]
Thanks! I'll wait impatiently :)

**Comment by muak** [comment]
@alexpetin 
Thank you for waiting.
This request has been implemented at ver.1.4.0-pre.
