### ISSUE TITLE
Usage in code behind c#

### ISSUE THREAD

**Issue by LeoJHarris** [muak/AiForms.Effects#28]
Hi there I am trying to add your your effects for the AddNumberPicker(), you have examples in XAML, can it be used in c#? If so how? I try something like this based on your xaml but getting error:

```
Button buttonAddQuantity = new Button()
            {
                AiForms.Effects.AddNumberPicker.SetOn(this,true),
            };
```

**Comment by muak** [comment]
@LeoJHarris 

Hi, please try the following code:

```xml
...omitted
<Button x:Name="myButton" />
```

```cs
AiForms.Effects.AddNumberPicker.SetOn(myButton, true);
AiForms.Effects.AddNumberPicker.SetMin(myButton, 1);
AiForms.Effects.AddNumberPicker.SetMax(myButton, 10);
```

An attached property must be specified the target control at first argument.

**Comment by LeoJHarris** [comment]
That works
