### ISSUE TITLE
NullReferenceException has occured when called Navigation.PopModalAsync with iOS

### ISSUE THREAD

**Issue by caramelopardalis** [muak/AiForms.Effects#29]
## Steps to Reproduce

Please see the attached solution and error log.

1. Tap a label (Push)

1. Tap a label (Hello, hello...)

1. NullReferenceException has occured

[fittosize.zip](https://github.com/muak/AiForms.Effects/files/1990472/fittosize.zip)
[error.log](https://github.com/muak/AiForms.Effects/files/1990473/error.log)

**Comment by muak** [comment]
@caramelopardalis 

Thank you for your report.

I am fixing this issue now.
Please wait until a new version is released.

**Comment by caramelopardalis** [comment]
Thanks!
