### ISSUE TITLE
Lower than Android 5.0 Crash

### ISSUE THREAD

**Issue by Wenfengcheng** [muak/AiForms.Effects#32]
```
BorderPlatformEffect.UpdateBorder ()
Java.Lang.IncompatibleClassChangeError: no method with name='setClipToOutline' signature='(Z)V' in class Lcom/xamarin/forms/platform/android/FormsViewGroup;
```
The ClipToOutline method is only available after Android 5.0.

**Comment by muak** [comment]
@Wenfengcheng 

I'm sorry,
This library is supported for more greater than or equal to Android 5.1.
https://github.com/muak/AiForms.Effects#minimum-device-and-version-etc

**Comment by Wenfengcheng** [comment]
I'm sorry to hear that,
But I tried to delete all the code related to 'setClipToOutline', which has no influences on the UI.

Does it mean that these lines of code relared to 'setClipToOutline' have no influences on the border effect?

**Comment by muak** [comment]
@Wenfengcheng 

'ClipToOutline ' stops a child view from overflowing from a parent view.
So removing them have an influence on borders of Layout views. The others such as Label and Button, as far as I remember, have no influence on the border effects.

Thanks.

**Comment by Wenfengcheng** [comment]
Thanks for your reply, I got it!

**Comment by Wenfengcheng** [comment]
@muak 

Thanks for your reply, I got it.
