### ISSUE TITLE
Border effect not worked when changing background color

### ISSUE THREAD

**Issue by Wenfengcheng** [muak/AiForms.Effects#35]
@muak 
I attach border effect to *Label*, it looks fine when the view loaded. But when I update the label background color, it also looks fine on iOS platform but the border effect is detached on Android.

**Comment by muak** [comment]
@Wenfengcheng 

Thank you for your reoport.

Would you tell me your AiForms.Effects version?

**Comment by Wenfengcheng** [comment]
@muak 

The *AiForms.Effects* version I used earlier was 1.3.1, I have upgraded *AiForms.Effects* to **1.4.0pre**, but it doesn't work.

**Comment by muak** [comment]
@Wenfengcheng 

Thank you for your information.

I will investigate the detail.
Please wait for a while.

**Comment by Wenfengcheng** [comment]
@muak 

I have forked your project, when I update the control backgroundcolor, **OnElementPropertyChanged** method will be invoked, but border effect is not attached to control again.

I add this code to *AiForms.Effects.Droid.BorderPlatformEffect.cs* file, add now it works fine:
```
            else if(args.PropertyName == View.BackgroundColorProperty.PropertyName)
            {
                UpdateColor();
                UpdateBorder();
            }
```

Maybe you can update this features and release new version again.

Best,
Wenfeng

**Comment by muak** [comment]
@Wenfengcheng 

Thank you so much for your investigation!
I incorporate it as soon as possible.

**Comment by muak** [comment]
@Wenfengcheng 

I released ver.1.4.4-pre just now.
Would you please try it?

I'm grateful to you for your help.
Thanks.

**Comment by Wenfengcheng** [comment]
@muak 

It worked!
Thank you for your update.
