### ISSUE TITLE
RepeatableStack resizes items while loading 

### ISSUE THREAD

**Issue by psp589** [muak/AiForms.Effects#40]
Using RepeatableStack, and load the items one by one, I see an ugly effect, the items gets its width resized every time a new item gets added. How could I prevent this? Am I doing something wrong? 
Thank you in advance.

**Comment by muak** [comment]
@psp589 

Don't you mistake AiForms.Effects for AiForms.Layouts?
For AiForms.Layouts, please post [here](https://github.com/muak/AiForms.Layouts/issues).

**Comment by psp589** [comment]
You're right, sorry
