### ISSUE TITLE
AndroidのAddText機能で文字が途切れる

### ISSUE THREAD

**Issue by takapi-Jr** [muak/AiForms.Effects#48]
こんにちは。こちらのライブラリを自作アプリに使わせていただいております。

エラーメッセージの表示にAddText機能を使用していますが、Androidの実機で確認すると、文字数が4文字の場合に「必須項…」のように途切れていました。
エミュレータで確認した場合は途切れずに表示されました。

【参考画像】
![Screenshot_20191025-200504-2](https://user-images.githubusercontent.com/25080529/67568724-f07e1e00-f767-11e9-8f8f-ca92e50c70d0.png)

**Comment by muak** [comment]
@takapi-Jr 
ご報告ありがとうございます。
大変お待たせしましたが、該当箇所を修正しました。
次期リリースに含まれる予定です。
リリースまでもう少々お待ちください。
