### ISSUE TITLE
Android OnOverlayTouch crash

### ISSUE THREAD

**Issue by TsChiEtA** [muak/AiForms.Effects#49]
We are using your effects library with Xamarin forms 4.2.0 and it mostly works like a charm.

Although we discovered a problem within the Android specific implementation of OnOverlayTouch when using the AddCommand. When the user rapidly hits controls triggering the models data to refresh, the app crashes with a NullReferenceException due to the _view field being null.

We simply added a null check to _view to fix the problem:

```csharp
void OnOverlayTouch(object sender, Android.Views.View.TouchEventArgs e)
{
    if (e.Event.Action == MotionEventActions.Down)
    {
        PlaySound();
    }

    _view?.DispatchTouchEvent(e.Event); // <-- Added null check

    e.Handled = false;
}
```

Maybe you could add this in the next release.

**Comment by muak** [comment]
@TsChiEtA 
Thank you for your report and your suggestion.

I adopted your code.
It will be reflected in the next release.

Thanks!
