### ISSUE TITLE
PlaySound not working for controls with EnableSound true

### ISSUE THREAD

**Issue by clnorris** [muak/AiForms.Effects#50]
I tried adding ef:Feedback.EnableSound="True" to a button in my view, and I didn't hear anything.

With the current expression in PlaySound(), only controls in the TapSoundEffectElementType list are allowed to play:
            if (_isTapTargetSoundEffect && _enableSound)

If I made this change, then the sound worked for my buttons:
            if (_isTapTargetSoundEffect || _enableSound)

I need ef:Feedback.EnableSound for buttons and other items in my views.  Could this fix to PlaySound() be done?

**Comment by muak** [comment]
@clnorris 
Thank you for your report.

As you said, a sound was not played on a button.
I added TapSoundEffectElementType to a type of button.

This is reflected in the next release.
Thanks.

**Comment by clnorris** [comment]
Thanks @muak for the quick fix, the sound on my button is working now.  Cheers!
