### ISSUE TITLE
AddCommand.SyncCanExecute does not work on Android

### ISSUE THREAD

**Issue by alexpetin** [muak/AiForms.Effects#53]
Hi! Thanks for this must-have lib!
It would be great to fix SyncCanExecute on Android, on iOS - it works well.

**Comment by alexpetin** [comment]
And it would be even more great to have possibility to somehow separate setting of IsEnabled and Opacity on sync - it would allow to customise disabled effect...

**Comment by muak** [comment]
@alexpetin 
I regret to say that I couldn't reproduce it. It works fine on my environment.
Could you show more detail?

About settings of IsEnabled and Opacity, I consider it.

**Comment by alexpetin** [comment]
Sorry, I had to be more detailed. On Android the tap effect occurs for disabled by SyncCanExecute items.

**Comment by muak** [comment]
@alexpetin 
Sorry, I can't reproduce it.
Could you offer a minimum reproducible project?

**Comment by alexpetin** [comment]
@muak 
[TestEffects.zip](https://github.com/muak/AiForms.Effects/files/4144139/TestEffects.zip)
[Video.zip](https://github.com/muak/AiForms.Effects/files/4144146/Video.zip)

**Comment by muak** [comment]
@alexpetin 
Thank you for your project files.

I fixed and released it.

Thanks!
