### ISSUE TITLE
System.NullReferenceException on Android on page close

### ISSUE THREAD

**Issue by alexpetin** [muak/AiForms.Effects#54]
Hi!

Page consist of CollectionView with ContentView Items with ef.AddCommand.
On PopAsync (using FreshMvvm btw) app crashes. Android only, iOS - no problem.

`
    Process: com.company.mobile, PID: 2026
    android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
      at AiForms.Effects.Droid.AiEffectBase+<>c__DisplayClass22_0.<BindingContextChanged>b__1 () [0x0000b] in <82332298958c45b498e83340cd785caa>:0 
      at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e98afaf88af5496ea979d99b06e991b9>:0 
      at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <e98afaf88af5496ea979d99b06e991b9>:0 
        at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.43(intptr,intptr)
`

**Comment by alexpetin** [comment]
Only Workaround is to set CollectionView ItemsSource to null at OnDisappearing...
Probably the crash occurs when FreshMvvm set BindingContext to null before page close.

**Comment by muak** [comment]
@alexpetin 
Though I don't know FreshMvvm, It works fine using Prism.Forms or ``Navigation.PopAsync()``.

I think that it crashes at the following:
https://github.com/muak/AiForms.Effects/blob/bd948f9e06e615909c692288a33955fde94f7274/AiForms.Effects.Droid/AiEffectBase.cs#L149-L165

If you know where the error occurs above, could you please tell me?

**Comment by alexpetin** [comment]
![image](https://user-images.githubusercontent.com/19589320/73594967-bdf17780-4545-11ea-93e0-0272147a7dd1.png)

@muak  `Element` is null here.

**Comment by alexpetin** [comment]
Also it looks like `OnDetached` is actually called in my case :)

![image](https://user-images.githubusercontent.com/19589320/73595180-25102b80-4548-11ea-8b87-32b2c3f98db9.png)

**Comment by alexpetin** [comment]
The problem disappears if I change that line to:

- `Device.BeginInvokeOnMainThread(() => Element?.Effects.Remove(toRemove));` or
- `Element.Effects.Remove(toRemove);`

Not sure what would be more correct. Btw why `BeginInvokeOnMainThread` was used here?

**Comment by muak** [comment]
@alexpetin 
Thank you for the information.

I will fix with the above.

Without ``BeginInvokeOnMainThread``,  there was the pattern of occurring error.
But I forgot what the pattern is.

Anyway, Thanks!
