### ISSUE TITLE
AddDatePicker crashes on old iOS versions

### ISSUE THREAD

**Issue by alexpetin** [muak/AiForms.Effects#65]
### Description
Starting release 1.6.9 using of AddDatePicker crashes app on old iOS versions with:

`Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UIDatePicker setPreferredDatePickerStyle:]: unrecognized selector sent `

Tried iOS 10.3, 11.2.6...

### Steps to Reproduce

1. Use AddDatePicker on page
2. Start app on iOS 10.3
3. See the crash

### Expected Behavior
No crash

### Actual Behavior
Crash

### Platforms

- [ ] Android
- [X] iOS

### Basic Information

- AiForms.Effects 1.6.9
- Xamarin.Forms x.x.x
- Android Support Library Version: 
- Affected Devices:

### Workaround
No workaround.
Prev. versions has AddDatePicker problem with iOS 14, 1.6.9 - with prev. iOS versions :(

**Comment by muak** [comment]
@alexpetin 
Thank you for your report.

This issue was fixed.
