### ISSUE TITLE
CanExecuteのチェック

### ISSUE THREAD

**Issue by yuka-abn** [muak/AiForms.Effects#9]
Command / LongCommandの実行時にCanExecueのチェックをおこなっていない実装ですが
何か特別が理由があるのでしょうか？

**Comment by muak** [comment]
@yuka-abn 
いえ、単に必要に迫られずの手抜き実装です。今週末あたりで時間があれば手を入れてみますね〜

**Comment by muak** [comment]
@yuka-abn 
CanExecuteをチェックするようにしました。
ついでにSyncCanExecuteというプロパティをtrueにした場合
FormsのIsEnabledプロパティと連動するようにして見た目もそれっぽくなるようにしました。
